### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by koaning** [raybellwaves/human-learn-binder#1]
It didn't occur to me to create a binder for `human-learn`. Would you mind if we populate it with an example notebook so folks can play immediately with it? I think the test-notebook should work swell for it. 

If possible, I wouldn't mind a PR on my own repo so we can add it to the docs.

**Comment by raybellwaves** [comment]
You may have gotten an e-mail where I tried to transfer owernship to you. Haven't done this below but i'm guessing it shows up in your profile? If that doesn't work welcome to clone and i'll delete mine so people can create issues off or yours.

**Comment by koaning** [comment]
Thanks!
